### PR TITLE
Feat: Add Reddit Discord GitHub buttons

### PR DESCRIPTION
**Pull request by ckvignesh**
Hi @evedes,
I've created a Heading Component for this that has buttons for WCC's socials.

### CODE REVIEW

**Comment by ckvignesh** [comment]
Hi @evedes.

Thanks for the feedback. I've changed the colours for the icons. Can you please check them and let me know if they're the ideal ones?

And are you still seeing the white space at the bottom?

**Comment by ckvignesh** [comment]
Hi @evedes.

I've changed the background colour and centred the icons. 

Working on centring the image here.

image

**Comment by ckvignesh** [comment]
Hi @evedes,

I've worked on the changes you suggested.
image

**Comment by evedes** [comment]
Good job @ckvignesh 🔥

**Comment by ckvignesh** [comment]
Thanks for merging, @evedes.

**Pull request merged**
